Domains::DomainUserTeachSkills
Domains.DomainUserTeachSkills.DomainUserTeachSkills(IRepositoryRole repositoryRole, IRepositoryJob repositoryJob, IRepositoryRoleContent repositoryRoleContent, IRepositoryMapingTeach repositoryMapingTeach, IRepositoryTeachSkills repositoryTeachSkills, IRepositoryTeachLever repositoryTeachLever)
ModelRole Domains.DomainUserTeachSkills.FindRole(int roleID)
根据角色ID查找某个角色
roleID
ModelProfessional Domains.DomainUserTeachSkills.FindJob(int jobID)
根据职业ID查找某个职业
jobID
ModelTechSkills Domains.DomainUserTeachSkills.FindTeachSkill(int skillID)
根据技能ID查询某个技能
skillID
List<ModelTeachLever> Domains.DomainUserTeachSkills.FindAllLever(int skillID)
根据技能ID查看技能下的所有等级分类
skillID
Referenced by Domains.DomainUserTeachSkills.FindJobAndSkillAndLever, Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayers, Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayersList.
ModelTeachLever Domains.DomainUserTeachSkills.FindOneLever(int teachSkillID, int leverID)
更具leverID查询某个具体的等级信息
leverID
List<ModelRoleAndJob> Domains.DomainUserTeachSkills.FindRoleAllJob(int roleID)
根据角色ID查询到该角色掌握的所有职业
roleID
Referenced by Domains.DomainUserTeachSkills.FindJobAndSkillAndLever, Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayers, Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayersList.
List<ModelJobAndTeachSkill> Domains.DomainUserTeachSkills.FindJobAllTeachSkill(int jobID)
根据职业ID查询该职业对应的所有技能
jobID
Referenced by Domains.DomainUserTeachSkills.FindJobAndSkillAndLever, Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayers, Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayersList.
List<ModelJobAndTeachSkill> Domains.DomainUserTeachSkills.FindTeachSkillAllJob(int TeachSkillID)
根据技能ID查询到技能对应的所有角色
jobID
Dictionary<ModelRoleAndJob, Dictionary<ModelJobAndTeachSkill, List<ModelTeachLever> > > Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayers(int roleID)
字典集合查询（类似于导航）
roleID
References Domains.DomainUserTeachSkills.FindAllLever, Domains.DomainUserTeachSkills.FindJobAllTeachSkill, Domains.DomainUserTeachSkills.FindRoleAllJob.
List<ModelJobAndTeachSkillAndLever> Domains.DomainUserTeachSkills.FindJobAndSkillAndLever(int roleID)
根据角色ID查询到所有的信息存储在联合三张表的ModelJobAndSkillAndLever大表中
roleID
References Domains.DomainUserTeachSkills.FindAllLever, Domains.DomainUserTeachSkills.FindJobAllTeachSkill, Domains.DomainUserTeachSkills.FindRoleAllJob.
List<Dictionary<ModelRoleAndJob, Dictionary<ModelJobAndTeachSkill, ModelTeachLever> > > Domains.DomainUserTeachSkills.FindJobAndSkillAndLeverThreeLayersList(int roleID)
字典集合查询（类似于表格）
roleID
References Domains.DomainUserTeachSkills.FindAllLever, Domains.DomainUserTeachSkills.FindJobAllTeachSkill, Domains.DomainUserTeachSkills.FindRoleAllJob.