Repositorys::RepositroyAssess
readonly DBContext Repositorys.RepositroyAssess.dbContext
Referenced by Repositorys.RepositroyAssess.FakeDelete, Repositorys.RepositroyAssess.Insert, Repositorys.RepositroyAssess.ReallyDelete.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindAllAssess()
查询所有的评价信息
Referenced by Repositorys.RepositroyAssess.FindAllDeleteAssess, Repositorys.RepositroyAssess.FindAllNotDeleteAssess, Repositorys.RepositroyAssess.FindByAssess, Repositorys.RepositroyAssess.FindMainAssess, Repositorys.RepositroyAssess.FindMainAssessToOneself.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindAllNotDeleteAssess()
查询所有未删除的评价信息 1未删除
References Repositorys.RepositroyAssess.FindAllAssess.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindAllDeleteAssess()
查询所有删除的评价信息 1未删除
References Repositorys.RepositroyAssess.FindAllAssess.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindByAssess(int id)
当前用户作为被评估对象
id 被评估人ID
References Repositorys.RepositroyAssess.FindAllAssess.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindMainAssess(int id)
当前对象为他人评估
id 评估人ID
References Repositorys.RepositroyAssess.FindAllAssess.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindMainAssessToOneself(int id)
当前对象为本身评估
id 评估人ID
References Repositorys.RepositroyAssess.FindAllAssess.
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindAssessCoreDetails(int id)
评估核心技能详细情况查询
id 评论摘要ID
List<ModelAssessDetails> Repositorys.RepositroyAssess.FindAssessTeachDetails(int id)
评估专业技能详细情况查询
id 评论摘要ID
bool Repositorys.RepositroyAssess.Insert(ModelEvaluation assess)
插入一条评论
assess
References Repositorys.RepositroyAssess.dbContext.
bool Repositorys.RepositroyAssess.FakeDelete(int id)
逻辑删除
id
References Repositorys.RepositroyAssess.dbContext.
bool Repositorys.RepositroyAssess.ReallyDelete(int id)
物理删除
id
References Repositorys.RepositroyAssess.dbContext.
bool Repositorys.RepositroyAssess.Update(ModelEvaluation assess)
更新
id