Domains::DomainUserCoreSkills
Domains.DomainUserCoreSkills.DomainUserCoreSkills(IRepositoryRole _repositoryRole, IRepositoryJob _repositoryJob, IRepositoryCoreSkills _repositoryCoreSkills, IRepositoryCoreLever _repositoryCoreLever, IRepositoryRoleContent _repositoryRoleContent, IRepositoryMapingCore _repositoryMapingCore)
ModelRole Domains.DomainUserCoreSkills.FindRole(int roleID)
根据角色ID查找某个角色
roleID
ModelProfessional Domains.DomainUserCoreSkills.FindJob(int jobID)
根据职业ID查找某个职业
jobID
ModelCoreSkills Domains.DomainUserCoreSkills.FindCoreSkill(int skillID)
根据技能ID查询某个技能
skillID
List<ModelCoreLever> Domains.DomainUserCoreSkills.FindAllLever(int skillID)
根据技能ID查看技能下的所有等级分类
skillID
Referenced by Domains.DomainUserCoreSkills.FindJobAndSkillAndLever, Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayers, Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayersList.
ModelCoreLever Domains.DomainUserCoreSkills.FindOneLever(int coreSkillID, int leverID)
更具leverID查询某个具体的等级信息
leverID
List<ModelRoleAndJob> Domains.DomainUserCoreSkills.FindRoleAllJob(int roleID)
根据角色ID查询到该角色掌握的所有职业
roleID
Referenced by Domains.DomainUserCoreSkills.FindJobAndSkillAndLever, Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayers, Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayersList.
List<ModelJobAndCoreSkill> Domains.DomainUserCoreSkills.FindJobAllCoreSkill(int jobID)
根据职业ID查询该职业对应的所有技能
jobID
Referenced by Domains.DomainUserCoreSkills.FindJobAndSkillAndLever, Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayers, Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayersList.
List<ModelJobAndCoreSkill> Domains.DomainUserCoreSkills.FindCoreSkillAllJob(int coreSkillID)
根据技能ID查询到技能对应的所有角色
jobID
Dictionary<ModelRoleAndJob, Dictionary<ModelJobAndCoreSkill, List<ModelCoreLever> > > Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayers(int roleID)
字典集合查询（类似于导航）
roleID
References Domains.DomainUserCoreSkills.FindAllLever, Domains.DomainUserCoreSkills.FindJobAllCoreSkill, Domains.DomainUserCoreSkills.FindRoleAllJob.
List<ModelJobAndSkillAndLever> Domains.DomainUserCoreSkills.FindJobAndSkillAndLever(int roleID)
根据角色ID查询到所有的信息存储在联合三张表的ModelJobAndSkillAndLever大表中
roleID
References Domains.DomainUserCoreSkills.FindAllLever, Domains.DomainUserCoreSkills.FindJobAllCoreSkill, Domains.DomainUserCoreSkills.FindRoleAllJob.
List<Dictionary<ModelRoleAndJob, Dictionary<ModelJobAndCoreSkill, ModelCoreLever> > > Domains.DomainUserCoreSkills.FindJobAndSkillAndLeverThreeLayersList(int roleID)
字典集合查询（类似于表格）
roleID
References Domains.DomainUserCoreSkills.FindAllLever, Domains.DomainUserCoreSkills.FindJobAllCoreSkill, Domains.DomainUserCoreSkills.FindRoleAllJob.