//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorys.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CoreLever
    {
        public int CoreLeverID { get; set; }
        public int CoreLeverNum { get; set; }
        public string CoreLeverDetails { get; set; }
        public int CoreSkillsID { get; set; }
    
        public virtual TB_CoreSkills TB_CoreSkills { get; set; }
    }
}
