//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorys.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CoreSkills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CoreSkills()
        {
            this.TB_CoreLever = new HashSet<TB_CoreLever>();
            this.TB_MappingCore = new HashSet<TB_MappingCore>();
        }
    
        public int CoreSkillsID { get; set; }
        public string CoreSkillsName { get; set; }
        public string CoreSkillsDetails { get; set; }
        public string CoreSkillsGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CoreLever> TB_CoreLever { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MappingCore> TB_MappingCore { get; set; }
    }
}
