//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorys.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EvaluationInfo
    {
        public int EvaluationInfoID { get; set; }
        public string SkillsGUID { get; set; }
        public int EvaluationID { get; set; }
        public int Lever { get; set; }
    
        public virtual TB_Evaluation TB_Evaluation { get; set; }
    }
}
