//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorys.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MappingTeach
    {
        public int MappingID { get; set; }
        public int ProfessionalID { get; set; }
        public int TeachSkillsID { get; set; }
    
        public virtual TB_Professional TB_Professional { get; set; }
        public virtual TB_TechSkills TB_TechSkills { get; set; }
    }
}
