//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorys.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TechSkills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TechSkills()
        {
            this.TB_MappingTeach = new HashSet<TB_MappingTeach>();
            this.TB_TeachLever = new HashSet<TB_TeachLever>();
        }
    
        public int TeachSkillsID { get; set; }
        public string TeachSkillsName { get; set; }
        public string TeachAkillsDetails { get; set; }
        public string TeachAkillsGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MappingTeach> TB_MappingTeach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TeachLever> TB_TeachLever { get; set; }
    }
}
