//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorys.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_UserInfo()
        {
            this.TB_Evaluation = new HashSet<TB_Evaluation>();
            this.TB_Evaluation1 = new HashSet<TB_Evaluation>();
        }
    
        public int UserInfoID { get; set; }
        public string UserInfoName { get; set; }
        public int UserInfoAge { get; set; }
        public string UserInfoAddress { get; set; }
        public string UserInfoBirthday { get; set; }
        public string UserPhone { get; set; }
        public string UserInfoEmail { get; set; }
        public string UserInfoWorkPhone { get; set; }
        public string UserCurrentAddress { get; set; }
        public string UserInfoQQ { get; set; }
        public string UserInfoDetails { get; set; }
        public int RoleID { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Evaluation> TB_Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Evaluation> TB_Evaluation1 { get; set; }
        public virtual TB_Role TB_Role { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
